per_listener_settings true


listener 1883 192.0.2.10
allow_anonymous false
password_file /etc/mosquitto/rescue.passwd
acl_file /etc/mosquitto/rescue.acl


persistence true
persistence_location /var/lib/mosquitto/
