#include "rescue_bridge/target_lifecycle.hpp"
#include <cassert>
#include <iostream>

int main() {
    using namespace rescue_execution;
    Target target{"AUDIT/a", "exec-a", 0, 22.0, 114.0, 5.0};
    TargetLifecycle lifecycle;
    assert(lifecycle.offer(target, false, "GPS_NOT_READY").status == "REJECTED");
    assert(!lifecycle.active());
    auto skipped = target; skipped.waypoint_index = 2;
    assert(lifecycle.offer(skipped, true, "").reason == "WAYPOINT_SEQUENCE_MISMATCH");
    auto accepted = lifecycle.offer(target, true, "");
    assert(accepted.status == "ACCEPTED" && accepted.publish_goal);
    assert(!lifecycle.offer(target, true, "").publish_goal);
    auto conflict = target; conflict.latitude += .1;
    assert(lifecycle.offer(conflict, true, "").reason == "TARGET_CONTENT_CONFLICT");
    auto second = target; second.waypoint_index = 1;
    assert(lifecycle.offer(second, true, "").reason == "TARGET_BUSY");
    assert(!lifecycle.arrived(1.0, 1.0));
    assert(!lifecycle.arrived(-1, 1.0));
    assert(!lifecycle.arrived(0, INFINITY));
    assert(lifecycle.arrived(.999, 1.0));
    assert(!lifecycle.arrived(0, 1.0));
    assert(lifecycle.offer(target, true, "").status == "ARRIVED");
    assert(lifecycle.offer(skipped, true, "").reason == "WAYPOINT_SEQUENCE_MISMATCH");
    assert(lifecycle.offer(second, true, "").publish_goal);
    auto other = target; other.execution_id = "exec-b";
    assert(lifecycle.offer(other, true, "").reason == "EXECUTION_LOCKED");
    assert(!lifecycle.control("AUDIT/a", "old", true));
    assert(lifecycle.control("AUDIT/a", "exec-a", false));
    assert(!lifecycle.active());
    assert(lifecycle.offer(second, true, "").reason == "EXECUTION_RELEASED");
    assert(lifecycle.offer(other, true, "").reason == "EXECUTION_LOCKED");
    assert(lifecycle.control("AUDIT/a", "exec-a", true));
    assert(lifecycle.offer(target, true, "").reason == "EXECUTION_RELEASED");
    assert(lifecycle.offer(other, true, "").publish_goal);
    Target maximum = target; maximum.waypoint_index = 100000;
    assert(TargetLifecycle::valid(maximum));
    maximum.waypoint_index = 100001; assert(!TargetLifecycle::valid(maximum));
    assert(!withinTarget(0, 0, 1, 1, 1));
    assert(withinTarget(.2, .3, .9, 1, 1));
    assert(!withinTarget(0, 0, NAN, 1, 1));
    assert(validQuaternion(0, 0, 0, 1));
    assert(!validQuaternion(0, 0, 0, 0));
    assert(!validQuaternion(0, NAN, 0, 1));
    assert(freshObservation(10, 9.9, 9.5, 1));
    assert(!freshObservation(10, 9.9, 8.9, 1));
    assert(!freshObservation(10, 10.1, 9.9, 1));
    assert(matchedObservations(10, 9.95, 9.75, 10, 10, 1));
    assert(!matchedObservations(10, 9.95, 9.749, 10, 10, 1));
    assert(!matchedObservations(10, 10, 10, 9.95, 9.749, 1));
    assert(!matchedObservations(10, 10, 8.9, 10, 9, 1));
    assert(!matchedObservations(10, 10.1, 9.9, 10, 9.9, 1));
    assert(!matchedObservations(10, 10, NAN, 10, 9.9, 1));
    assert(!matchedObservations(10, 10, 0, 10, 0, 20));
    assert(!matchedObservations(10, 10, 10, 10, 10, 1, -1));
    const double pi = std::acos(-1.0);
    const auto east = gpsToEastNorth(0, 0, 0, .001);
    const auto north = gpsToEastNorth(0, 0, .001, 0);
    assert(east.x > 100 && std::abs(east.y) < 1e-8);
    assert(north.y > 100 && std::abs(north.x) < 1e-8);
    assert(gpsToEastNorth(0, 179.999, 0, -179.999).x < 300);
    for (double rotation : {0., pi/2, pi, -pi/2}) {
        FrameAlignment frame;
        bool rejected = false;
        try { frame.transform({1, 0}); } catch (const std::logic_error&) { rejected = true; }
        assert(rejected);
        assert(!frame.calibrate({1, 0}, {0, 1}));
        assert(frame.calibrate({10, 0}, {10*std::cos(rotation), 10*std::sin(rotation)}));
        for (PlanarVector vector : {PlanarVector{10, 0}, {0, 10}, {-10, 0}, {0, -10}}) {
            const auto result = frame.transform(vector);
            assert(std::abs(result.x - (std::cos(rotation)*vector.x - std::sin(rotation)*vector.y)) < 1e-8);
            assert(std::abs(result.y - (std::sin(rotation)*vector.x + std::cos(rotation)*vector.y)) < 1e-8);
        }
        frame.reset(); assert(!frame.ready());
    }
    TargetLifecycle height;
    height.offer(target, true, "");
    assert(!height.arrived3d(0, 0, 2, 1, 1));
    assert(height.active());
    assert(height.arrived3d(0, 0, .9, 1, 1));
    CoordinateFrameState frame_state;
    FrameAlignment recalibration;
    TargetLifecycle tracked;
    assert(!frame_state.observe("vins-a", true, false));
    assert(recalibration.calibrate({10, 0}, {10, 0}));
    assert(tracked.offer(target, true, "").publish_goal);
    assert(!frame_state.observe("vins-a", false, true));
    assert(frame_state.observe("vins-b", true, true));
    assert(frame_state.targetInvalidated());
    recalibration.reset();
    assert(!recalibration.ready());
    assert(recalibration.calibrate({10, 0}, {0, 10}));
    assert(recalibration.ready());
    assert(frame_state.targetInvalidated());
    assert(!frame_state.observe("vins-b", true, true));
    const auto invalid_target = tracked.offer(target, !frame_state.targetInvalidated(), "COORDINATE_FRAME_CHANGED");
    assert(invalid_target.status == "REJECTED" && invalid_target.reason == "COORDINATE_FRAME_CHANGED");
    assert(!invalid_target.publish_goal);
    assert(!tracked.control("AUDIT/a", "wrong-execution", true));
    assert(frame_state.targetInvalidated());
    assert(tracked.control("AUDIT/a", "exec-a", false));
    assert(frame_state.targetInvalidated());
    assert(tracked.control("AUDIT/a", "exec-a", true));
    frame_state.releaseTarget();
    assert(!frame_state.targetInvalidated());
    assert(tracked.offer(target, true, "").reason == "EXECUTION_RELEASED");
    assert(tracked.offer(other, true, "").publish_goal);
    CoordinateFrameState preflight;
    assert(!preflight.observe("vins-a", true, false));
    assert(preflight.observe("vins-b", true, false));
    assert(!preflight.targetInvalidated());
    assert(!preflight.observe("vins-b", true, true));
    assert(!preflight.targetInvalidated());
    assert(!preflight.observe("vins-c", false, true));
    assert(preflight.observe("vins-c", true, true));
    assert(preflight.targetInvalidated());
    assert(preflight.observe("vins-b", true, true));
    assert(preflight.targetInvalidated());
    std::cout << "target lifecycle: readiness, identity, deduplication, arrival, frame invalidation, paired positions and release assertions passed\n";
}
